name: '$(BuildDefinitionName)_$(Build.SourceBranchName)_$(Major).$(Minor).$(Patch)'

variables:
- name: Major
  value: 1
- name: Minor
  value: 0
- name: Patch
  value: $[counter(format('{0}.{1}', variables['Major'], variables['Minor']), 0)]


resources:
  repositories:
    - repository: organization-infra
      type: git
      name: "product development/organization-infra"

trigger:
    batch: true
    tags:
        include:
            - "*"
    branches:
        include:
            - main
    paths:
        include:
            - src
        exclude:
            - docs

pool: "Agent Pool organization"

stages:
  - stage: "Build"
    jobs:
    - deployment: build
      continueOnError: false
      environment: 'dev'
      variables:
      - group: dev-key-vault-credential
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - template: 'templates/installJava.yml@organization-infra'

              - script: |
                  rm src/Organization.Db.Migrations.Tools.App/appsettings.json
                continueOnError: false
                displayName: "02 - Delete Current appsettings.json"

              - template: 'templates/installSOPS.yml@organization-infra'

              - template: 'templates/decryptSOPS.yml@organization-infra'
                parameters:
                    FileToDecryptFileWithPath: "$(System.DefaultWorkingDirectory)/src/Organization.Db.Migrations.Tools.App/appsettings.$(environment.name).enc.json"
                    DecryptedFileWithPath: "$(System.DefaultWorkingDirectory)/src/Organization.Db.Migrations.Tools.App/appsettings.json"

              - template: "templates/dotnetBuild.yml@organization-infra"
                parameters:
                    SonarProjectKey: 'organization_organization-db-migrations-tools'
                    SonarProjectName: 'organization-db-migrations-tools'
                    PublishProject: 'Organization.Db.Migrations.Tools.App.csproj'

              - template: "templates/snykTest.yml@organization-infra"
                parameters:
                  SolutionPath: "./src/Organization.Db.Migrations.Tools.App.sln"

  - stage: "Build_sta"
    dependsOn: "Build"
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], '-rc'))
    jobs:
    - deployment: build
      continueOnError: false
      environment: 'sta'
      variables:
      - group: dev-key-vault-credential
      strategy:
       runOnce:
         deploy:
           steps:
             - checkout: self

             - template: 'templates/installJava.yml@organization-infra'
             - template: 'templates/installSOPS.yml@organization-infra'
             - template: 'templates/decryptSOPS.yml@organization-infra'
               parameters:
                    FileToDecryptFileWithPath: "$(System.DefaultWorkingDirectory)/src/Organization.Db.Migrations.Tools.App/appsettings.$(environment.name).enc.json"
                    DecryptedFileWithPath: "$(System.DefaultWorkingDirectory)/src/Organization.Db.Migrations.Tools.App/appsettings.json"

             - template: 'templates/dotnetBuild.yml@organization-infra'
               parameters:
                SonarProjectKey: "organization_organization-db-migrations-tools"
                SonarProjectName: "organization-db-migrations-tools"
                PublishProject: "Organization.Db.Migrations.Tools.App.Web.csproj"

  - stage: "Build_prd"
    dependsOn: "Build"
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], '-ga'))
    jobs:
    - deployment: build
      continueOnError: false
      environment: 'prd'
      variables:
      - group: dev-key-vault-credential
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - template: 'templates/installJava.yml@organization-infra'

              - template: 'templates/installSOPS.yml@organization-infra'

              - template: 'templates/decryptSOPS.yml@organization-infra'
                parameters:
                    FileToDecryptFileWithPath: "$(System.DefaultWorkingDirectory)/src/Organization.Db.Migrations.Tools.App/appsettings.$(environment.name).enc.json"
                    DecryptedFileWithPath: "$(System.DefaultWorkingDirectory)/src/Organization.Db.Migrations.Tools.App/appsettings.json"

              - template: 'templates/dotnetBuild.yml@organization-infra'
                parameters:
                  SonarProjectKey: "organization_organization-db-migrations-tools"
                  SonarProjectName: "organization-db-migrations-tools"
                  PublishProject: "Organization.Db.Migrations.Tools.App.Web.csproj"
